apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: james-smart-vol
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
