apiVersion: v1
kind: Pod
metadata:
  name: j-pod-empty
  namespace: guru-research
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - perfsonar.csusb.edu
                  - nrp-c5.nysernet.org
  containers:
    - name: demo
      image: alpine/git
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "sleep infinity",
        ]
      volumeMounts:
        - name: james-smart-vol
          mountPath: /data
        - name: james-data-vol
          mountPath: /storage
        - name: emptyvol
          mountPath: /opt/repo
      resources:
        limits:
          memory: 12Gi
          cpu: "2"
          nvidia.com/gpu: "1"
        requests:
          memory: 12Gi
          cpu: "2"
          nvidia.com/gpu: "1"
  volumes:
    - name: james-smart-vol
      persistentVolumeClaim:
        claimName: james-smart-vol
    - name: james-data-vol
      persistentVolumeClaim:
        claimName: james-data-vol
    - name: emptyvol
      emptyDir: {}