apiVersion: v1
kind: Pod
metadata:
  name: j-pod-lightning
  namespace: guru-research
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - perfsonar.csusb.edu
  containers:
  - name: demo
    image: cyoung02/smart:latest
    command: ["/bin/bash"]
    # /data/scripts/init.sh; 
    args: 
    - "-c"
    - >- 
      cd /workspace &&
      git clone https://jameszhao01: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@github.com/Cyoung02/smart4.5.git &&
      chmod u+x -R /workspace/smart4.5/scripts &&
      sleep infinity
    volumeMounts:
      - name: james-smart-vol
        mountPath: /data
      - name: james-data-vol
        mountPath: /storage
      - name: dshm
        mountPath: /dev/shm
    resources:
      limits:
        memory: 12Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 12Gi
        cpu: "2"
        nvidia.com/gpu: "1"
  volumes:
    - name: james-smart-vol
      persistentVolumeClaim:
        claimName: james-smart-vol
    - name: james-data-vol
      persistentVolumeClaim:
        claimName: james-data-vol
    - name: dshm
      emptyDir:
        medium: Memory
  imagePullSecrets:
    - name: gitlab-auth
