apiVersion: batch/v1
kind: Job
metadata:
  name: j-job-lightning
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - perfsonar.csusb.edu
                      - prp-gpu-3.t2.ucsd.edu
      containers:
      - name: demo
        image: cyoung02/smart:latest
        command: ["/bin/bash"]
        # /data/scripts/init.sh; 
        args: 
        - "-c"
        - >- 
          cd /workspace &&
          git clone https://jameszhao01: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@github.com/Cyoung02/smart4.5.git &&
          chmod u+x -R /workspace/smart4.5/scripts &&
          /workspace/smart4.5/scripts/cp_new_pair_data.sh && 
          cd /workspace/smart4.5 &&
          python train.py
        volumeMounts:
          - name: james-smart-vol
            mountPath: /data
          - name: james-data-vol
            mountPath: /storage
          - name: dshm
            mountPath: /dev/shm
        resources:
          limits:
            memory: 24Gi
            cpu: "4"
            nvidia.com/gpu: "1"
          requests:
            memory: 24Gi
            cpu: "4"
            nvidia.com/gpu: "1"
      volumes:
        - name: james-smart-vol
          persistentVolumeClaim:
            claimName: james-smart-vol
        - name: james-data-vol
          persistentVolumeClaim:
            claimName: james-data-vol
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
      imagePullSecrets:
        - name: gitlab-auth
  backoffLimit: 6
