apiVersion: v1
kind: Pod
metadata:
  name: j-pod
  namespace: guru-research
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - perfsonar.csusb.edu
                  - nrp-c5.nysernet.org
  containers:
    - name: generic
      image: hammad001/pytorch-cuda-basic:0.0.1
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
      resources:
        requests:
          memory: "8Gi"
          cpu: 1
        limits:
          memory: "8Gi"
          cpu: 1
      volumeMounts:
        - name: james-smart-volume
          mountPath: /data
        - name: emptyvol
          mountPath: /opt/repo
  volumes:
    - name: james-smart-volume
      persistentVolumeClaim:
        claimName: james-smart-volume
